// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DailyCheckDbContext))]
    partial class DailyCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Data.Checkin", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly>("CheckDate")
                        .HasColumnType("date")
                        .HasColumnName("check_date")
                        .HasComment("打卡日期（仅日期）");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at")
                        .HasComment("伪删除时间");

                    b.Property<string>("Images")
                        .HasColumnType("json")
                        .HasColumnName("images")
                        .HasComment("打卡图片URL数组(JSON)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否伪删除：0正常，1已删除");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note")
                        .HasComment("打卡备注");

                    b.Property<ulong>("PlanId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("plan_id")
                        .HasComment("所属打卡计划ID");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status")
                        .HasComment("打卡状态：0错过(红)、1成功(绿)、2补签(黄)");

                    b.Property<ulong?>("TimeSlotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("time_slot_id")
                        .HasComment("关联的打卡时间段ID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新时间");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("打卡用户ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TimeSlotId" }, "fk_checkins_time_slot");

                    b.HasIndex(new[] { "IsDeleted" }, "idx_checkins_is_deleted");

                    b.HasIndex(new[] { "Status" }, "idx_checkins_status");

                    b.HasIndex(new[] { "UserId", "CheckDate" }, "idx_checkins_user_date");

                    b.HasIndex(new[] { "PlanId", "CheckDate", "TimeSlotId" }, "ux_checkins_plan_date_slot")
                        .IsUnique();

                    b.ToTable("checkins", null, t =>
                        {
                            t.HasComment("打卡记录表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.CheckinPlan", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at")
                        .HasComment("伪删除时间");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("打卡计划描述");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date")
                        .HasComment("计划结束日期（可选）");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'")
                        .HasComment("是否启用：1启用，0停用");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否伪删除：0正常，1已删除");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date")
                        .HasComment("计划开始日期");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title")
                        .HasComment("打卡计划标题");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新时间");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("计划所属用户ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsActive" }, "idx_plans_is_active");

                    b.HasIndex(new[] { "IsDeleted" }, "idx_plans_is_deleted");

                    b.HasIndex(new[] { "StartDate" }, "idx_plans_start_date");

                    b.HasIndex(new[] { "UserId" }, "idx_plans_user");

                    b.ToTable("checkin_plans", null, t =>
                        {
                            t.HasComment("打卡计划表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.CheckinPlanTimeSlot", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("创建时间");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time")
                        .HasComment("结束时间（如 10:00:00）");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'")
                        .HasComment("是否启用：1启用，0停用");

                    b.Property<ushort>("OrderNum")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("order_num")
                        .HasComment("排序序号，用于界面展示顺序");

                    b.Property<ulong>("PlanId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("plan_id")
                        .HasComment("所属打卡计划ID");

                    b.Property<string>("SlotName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slot_name")
                        .HasComment("时间段名称，如“早晨”、“下午”");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time")
                        .HasComment("开始时间（如 09:00:00）");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新时间");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsActive" }, "idx_slots_active");

                    b.HasIndex(new[] { "PlanId" }, "idx_slots_plan");

                    b.ToTable("checkin_plan_time_slots", null, t =>
                        {
                            t.HasComment("打卡计划时间段配置表（每日重复）");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.SoftDeleteLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("伪删除时间");

                    b.Property<ulong?>("DeleterUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("deleter_user_id")
                        .HasComment("执行伪删除操作的用户ID");

                    b.Property<string>("Extra")
                        .HasColumnType("json")
                        .HasColumnName("extra")
                        .HasComment("扩展信息(JSON)，如数据快照等");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason")
                        .HasComment("伪删除原因");

                    b.Property<ulong>("RecordId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("record_id")
                        .HasComment("被伪删除记录的主键ID");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("table_name")
                        .HasComment("伪删除记录所属表名");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DeleterUserId" }, "fk_soft_delete_deleter");

                    b.HasIndex(new[] { "DeletedAt" }, "idx_soft_delete_deleted_at");

                    b.HasIndex(new[] { "TableName", "RecordId" }, "idx_soft_delete_table_record");

                    b.ToTable("soft_delete_logs", null, t =>
                        {
                            t.HasComment("伪删除操作日志表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("AccountUpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("account_updated_at")
                        .HasComment("username更新时间");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("avatar_key")
                        .HasComment("头像图片URL");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at")
                        .HasComment("伪删除时间");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("用户邮箱（唯一）");

                    b.Property<ulong?>("FreezeOperatorId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("freeze_operator_id")
                        .HasComment("执行冻结操作的管理员用户ID");

                    b.Property<DateTime?>("FrozenAt")
                        .HasColumnType("datetime")
                        .HasColumnName("frozen_at")
                        .HasComment("账户冻结时间");

                    b.Property<string>("FrozenReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("frozen_reason")
                        .HasComment("账户冻结原因");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted")
                        .HasComment("是否伪删除：0正常，1已删除");

                    b.Property<string>("NickName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("nick_name")
                        .HasComment("用户昵称");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash")
                        .HasComment("密码哈希（如bcrypt）");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('user','admin')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'")
                        .HasComment("用户角色：user普通用户，admin管理员");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'")
                        .HasComment("账户状态：1正常，0冻结");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新时间");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_account")
                        .HasComment("用户账号（唯一）");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FreezeOperatorId" }, "fk_users_freeze_operator");

                    b.HasIndex(new[] { "FrozenAt" }, "idx_users_frozen_at");

                    b.HasIndex(new[] { "IsDeleted" }, "idx_users_is_deleted");

                    b.HasIndex(new[] { "Status" }, "idx_users_status");

                    b.HasIndex(new[] { "Email" }, "ux_users_email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("用户表（支持伪删除与黑名单冻结）");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.UserActivity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action")
                        .HasComment("操作名称/事件标识");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("记录时间");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip")
                        .HasComment("IP地址");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata")
                        .HasComment("扩展元数据(JSON)，参数等");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("path")
                        .HasComment("页面路径或操作路径");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("user_agent")
                        .HasComment("User-Agent信息");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("用户ID（匿名操作可为空）");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_activity_created");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_activity_user_created");

                    b.ToTable("user_activity", null, t =>
                        {
                            t.HasComment("用户行为埋点日志表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.UserBlacklistRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("操作发生时间");

                    b.Property<ulong?>("OperatorUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("operator_user_id")
                        .HasComment("执行操作的管理员用户ID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reason")
                        .HasComment("拉黑或解封原因");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasComment("状态：1拉黑，0解封（历史记录）");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("被拉黑的用户ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OperatorUserId" }, "fk_blacklist_operator");

                    b.HasIndex(new[] { "UserId", "OccurredAt" }, "idx_blacklist_user");

                    b.ToTable("user_blacklist_records", null, t =>
                        {
                            t.HasComment("用户黑名单记录表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.UserOauthAccount", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id")
                        .HasComment("主键ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("绑定时间");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("open_id")
                        .HasComment("第三方平台open_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("enum('wechat','google','apple')")
                        .HasColumnName("provider")
                        .HasComment("第三方登录平台类型");

                    b.Property<string>("UnionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("union_id")
                        .HasComment("第三方平台union_id（可选）");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("更新时间");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id")
                        .HasComment("关联用户ID");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "idx_oauth_user");

                    b.HasIndex(new[] { "Provider", "OpenId" }, "ux_oauth_provider_open")
                        .IsUnique();

                    b.ToTable("user_oauth_accounts", null, t =>
                        {
                            t.HasComment("用户第三方登录账号绑定表");
                        });

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("api.Data.Checkin", b =>
                {
                    b.HasOne("api.Data.CheckinPlan", "Plan")
                        .WithMany("Checkins")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("fk_checkins_plan");

                    b.HasOne("api.Data.CheckinPlanTimeSlot", "TimeSlot")
                        .WithMany("Checkins")
                        .HasForeignKey("TimeSlotId")
                        .HasConstraintName("fk_checkins_time_slot");

                    b.HasOne("api.Data.User", "User")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_checkins_user");

                    b.Navigation("Plan");

                    b.Navigation("TimeSlot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Data.CheckinPlan", b =>
                {
                    b.HasOne("api.Data.User", "User")
                        .WithMany("CheckinPlans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_plans_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Data.CheckinPlanTimeSlot", b =>
                {
                    b.HasOne("api.Data.CheckinPlan", "Plan")
                        .WithMany("CheckinPlanTimeSlots")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_plan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("api.Data.SoftDeleteLog", b =>
                {
                    b.HasOne("api.Data.User", "DeleterUser")
                        .WithMany("SoftDeleteLogs")
                        .HasForeignKey("DeleterUserId")
                        .HasConstraintName("fk_soft_delete_deleter");

                    b.Navigation("DeleterUser");
                });

            modelBuilder.Entity("api.Data.User", b =>
                {
                    b.HasOne("api.Data.User", "FreezeOperator")
                        .WithMany("InverseFreezeOperator")
                        .HasForeignKey("FreezeOperatorId")
                        .HasConstraintName("fk_users_freeze_operator");

                    b.Navigation("FreezeOperator");
                });

            modelBuilder.Entity("api.Data.UserBlacklistRecord", b =>
                {
                    b.HasOne("api.Data.User", "OperatorUser")
                        .WithMany("UserBlacklistRecordOperatorUsers")
                        .HasForeignKey("OperatorUserId")
                        .HasConstraintName("fk_blacklist_operator");

                    b.HasOne("api.Data.User", "User")
                        .WithMany("UserBlacklistRecordUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_blacklist_user");

                    b.Navigation("OperatorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Data.UserOauthAccount", b =>
                {
                    b.HasOne("api.Data.User", "User")
                        .WithMany("UserOauthAccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_oauth_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Data.CheckinPlan", b =>
                {
                    b.Navigation("CheckinPlanTimeSlots");

                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("api.Data.CheckinPlanTimeSlot", b =>
                {
                    b.Navigation("Checkins");
                });

            modelBuilder.Entity("api.Data.User", b =>
                {
                    b.Navigation("CheckinPlans");

                    b.Navigation("Checkins");

                    b.Navigation("InverseFreezeOperator");

                    b.Navigation("SoftDeleteLogs");

                    b.Navigation("UserBlacklistRecordOperatorUsers");

                    b.Navigation("UserBlacklistRecordUsers");

                    b.Navigation("UserOauthAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
