/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckInTab: typeof import('./components/tabs/CheckInTab.vue')['default']
    CustomTabBar: typeof import('./components/CustomTabBar.vue')['default']
    HomeTab: typeof import('./components/tabs/HomeTab.vue')['default']
    NotificationSystem: typeof import('./components/NotificationSystem.vue')['default']
    ProgressRing: typeof import('./components/ProgressRing.vue')['default']
    QfImageCropper: typeof import('./components/qf-image-cropper/qf-image-cropper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsTab: typeof import('./components/tabs/SettingsTab.vue')['default']
  }
}

// For TSX support
declare global {
  const CheckInTab: typeof import('./components/tabs/CheckInTab.vue')['default']
  const CustomTabBar: typeof import('./components/CustomTabBar.vue')['default']
  const HomeTab: typeof import('./components/tabs/HomeTab.vue')['default']
  const NotificationSystem: typeof import('./components/NotificationSystem.vue')['default']
  const ProgressRing: typeof import('./components/ProgressRing.vue')['default']
  const QfImageCropper: typeof import('./components/qf-image-cropper/qf-image-cropper.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsTab: typeof import('./components/tabs/SettingsTab.vue')['default']
}