/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    Example: typeof import('./components/FilePreview/example.vue')['default']
    FilePreview: typeof import('./components/FilePreview/index.vue')['default']
    GlobalIcon: typeof import('./components/GlobalIcon/index.vue')['default']
    MusicPlayer: typeof import('./components/MiniAudioPlayer/components/music-player.vue')['default']
    NotificationSystem: typeof import('./components/NotificationSystem/index.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar/index.vue')['default']
    ProgressiveAvatar: typeof import('./components/ProgressiveAvatar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./components/Menu/SettingsMenu.vue')['default']
    SettingsMenuItem: typeof import('./components/Menu/SettingsMenuItem.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Text: typeof import('./components/Text/index.vue')['default']
    ToWebM: typeof import('./components/ToWebM/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
