/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckinDetailDrawer: typeof import('./src/components/CheckinDetailDrawer.vue')['default']
    CheckinDrawer: typeof import('./src/components/CheckinDrawer.vue')['default']
    CreatePlanDrawer: typeof import('./src/components/CreatePlanDrawer.vue')['default']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ImagePreviewList: typeof import('./src/components/ImagePreviewList.vue')['default']
    NotificationSystem: typeof import('./src/components/NotificationSystem.vue')['default']
    PlanSidebar: typeof import('./src/components/PlanSidebar.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
  }
}
